// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deficiencies.sql

package database

import (
	"context"
)

const getDeficiencyByID = `-- name: GetDeficiencyByID :one
SELECT id, name, description, treatment FROM nutrient_deficiencies WHERE id = $1
`

func (q *Queries) GetDeficiencyByID(ctx context.Context, id int64) (NutrientDeficiency, error) {
	row := q.db.QueryRowContext(ctx, getDeficiencyByID, id)
	var i NutrientDeficiency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Treatment,
	)
	return i, err
}
