// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: symptoms.sql

package database

import (
	"context"
)

const getAllSymptoms = `-- name: GetAllSymptoms :many
SELECT id, name, description FROM symptoms
ORDER BY name
`

func (q *Queries) GetAllSymptoms(ctx context.Context) ([]Symptom, error) {
	rows, err := q.db.QueryContext(ctx, getAllSymptoms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Symptom
	for rows.Next() {
		var i Symptom
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
