// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"encoding/json"
)

type DiagnosticRule struct {
	ID             int32
	PlantID        sql.NullInt32
	ConditionsJson json.RawMessage
	DeficiencyID   int32
	CreatedAt      sql.NullTime
}

type NutrientDeficiency struct {
	ID          int32
	Name        string
	Description string
	Causes      string
	Treatment   string
	CreatedAt   sql.NullTime
}

type Plant struct {
	ID             int32
	Name           string
	ScientificName string
	CreatedAt      sql.NullTime
}

type PlantSymptom struct {
	PlantID        sql.NullInt64
	SymptomID      sql.NullInt64
	SeverityWeight sql.NullInt32
}

type Symptom struct {
	ID          int32
	Name        string
	Description string
	CreatedAt   sql.NullTime
}

type SymptomDeficiency struct {
	ID              int32
	SymptomID       int32
	DeficiencyID    int32
	ConfidenceScore string
	CreatedAt       sql.NullTime
}
